# Numpy

### Lists Recap
- powerful
- collection of values
- Hold different types
- change, add, remove
- Need for data Sciencce ?
    - Mathematical Operations Over Collections
    - Speed

### Illustration of Analysis

In [1]:
height = [4.35, 5.43, 7, 3.56]
weight = [40.5, 56.7, 76.3, 54.7]

weight / height ** 2

<class 'TypeError'>: unsupported operand type(s) for ** or pow(): 'list' and 'int'

### Solution: NUMPY
- Numeric Python
- Alternative to Python List: Numpy Array
- Calculations Over entire Array
- Easy & Fast
- Installation
    - In the terminal: `pip install numpy`

In [2]:
import numpy as np
np_height = np.array(height)
np_weight = np.array(weight)

bmi = np_weight / np_height ** 2
bmi

array([2.14030916, 1.92301822, 1.55714286, 4.31605858])

### Numpy: remarks
- variety of elements
- operators action on list vs arrays

In [3]:
np.array([4.34, 'is', True]) #In list we can keep multiple data types but in np array we will have to keep same datatype

array(['4.34', 'is', 'True'], dtype='<U32')

#### Different Types = Different Behaviour!

In [4]:
python_list = [1, 2, 3, 4]
numpy_array = np.array([1, 2, 3, 4])

In [5]:
python_list + python_list #python list will append all values

[1, 2, 3, 4, 1, 2, 3, 4]

In [6]:
numpy_array + numpy_array #numpy will perform addition

array([2, 4, 6, 8])

### Numpy Subsetting

In [7]:
bmi

array([2.14030916, 1.92301822, 1.55714286, 4.31605858])

In [8]:
bmi[2]

1.5571428571428572

In [9]:
bmi > 2

array([ True, False, False,  True])

In [10]:
bmi[bmi > 2]

array([2.14030916, 4.31605858])

# 2D Numpy Arrays
- array.ndim() & type(array)

In [11]:
print(np_height)
print(np_weight)

[4.35 5.43 7.   3.56]
[40.5 56.7 76.3 54.7]


In [12]:
type(np_height)

numpy.ndarray

In [13]:
np_height.ndim #-->numpy dimension

1

In [14]:
np_2d = np.array([[4.35, 5.43, 7, 3.56],
                  [40.5, 56.7, 76.3, 54.7]])

In [15]:
np_2d.ndim

2

In [16]:
np_2d.shape #2 rows and 4 colums

(2, 4)

### Subsetting on 2 dimensions

In [17]:
np_2d

array([[ 4.35,  5.43,  7.  ,  3.56],
       [40.5 , 56.7 , 76.3 , 54.7 ]])

In [18]:
np_2d[0]

array([4.35, 5.43, 7.  , 3.56])

In [19]:
np_2d[0][1:3] # first brakets will show rows and 2nd bratets will show columns

array([5.43, 7.  ])

In [20]:
np_2d[:, 2:] #The value before the cooma will represent the rows and after the cooma columns

array([[ 7.  ,  3.56],
       [76.3 , 54.7 ]])

In [21]:
np_2d [1,:]

array([40.5, 56.7, 76.3, 54.7])

### Numpy: Basic Statistics

- Data analysis
    - Get to know your data
    - Little data -> Simply Look at it
    - big data -> ??

- np.mean(), np.median(), np.mode(), np.corrcoef(), np.std(), np.sort() <br>
- np_city[:,0]

In [28]:
import numpy as np

np_city = np.array([[1.64, 71.78],[1.37, 63.35], [1.76, 55.09],[2.04, 74.85],[2.04, 68.72],[2.01, 73.57],
                   [2.64, 73.78],[3.37, 65.35], [4.76, 65.09],[5.04, 76.85],[6.04, 68.72],[7.01, 73.67],
                   [1.64, 71.78],[1.37, 63.35], [1.76, 55.09],[2.04, 74.85],[2.04, 68.72],[2.01, 73.57]])

In [23]:
np.mean(np_city[:, 1])

68.78777777777776

In [24]:
np.median(np_city[0,:])

36.71

In [25]:
np.sum(np_city[:, 0])

50.58

In [26]:
np.corrcoef(np_city[:, 0])

1.0

In [27]:
np.sort(np_city[0, 0:2])

array([ 1.64, 71.78])

- sum(), sort(), ...
- Enforce single data type: speed!

### Generate data
- Arguments for np.random.normal() --> np.column_stack(())
- distribution mean
- distribution standard deviation
- number of samples

In [33]:
random_height = np.round(np.random.normal(4.4, 7, 25), 2)
random_weight = np.round(np.random.normal(40.2, 75, 25), 2)

np_city1 = np.column_stack((random_height, random_weight))
np_city1

array([[ 11.99,  10.5 ],
       [ 13.  ,  32.56],
       [  8.92,  41.41],
       [  5.32,  52.15],
       [  4.62, 105.52],
       [ 21.96,  49.68],
       [ -7.48, -88.58],
       [-14.02,  64.92],
       [  4.99, -57.14],
       [  7.32, -18.18],
       [  5.85,  28.71],
       [ 10.4 , 155.07],
       [  2.84,  76.48],
       [  6.58,  61.14],
       [  4.65,  52.52],
       [  1.22, 117.  ],
       [ 15.66,  33.29],
       [ 12.53,  92.68],
       [  3.92, -29.88],
       [ 12.56,  44.6 ],
       [ 14.92, -59.16],
       [  7.53,  42.65],
       [  7.01,  34.61],
       [ 14.29,  83.68],
       [ -4.31,  49.83]])